### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by tsmgeek** [lazzard/php-ftp-bridge#1]
Is there any plan to add SSL support or does it support it already?

**Comment by AmraniCh** [comment]
Hey, Thanks for opening this issue.

The explicit FTP over SSL/TLS ([rfc2228](https://datatracker.ietf.org/doc/html/rfc2228)) support will be added in the next versions, we want the first stable version to support secure connections (FTPS), however, I'll update the `TODO.md` file with the things that must be included in the next versions, thanks for your interest.
